@baseUrl = http://localhost:3333
@authToken = {{authenticate.response.body.access_token}}

# @name create_account
POST {{baseUrl}}/accounts
Content-Type: application/json

{
  "name": "Maria dos Santos",
  "position": "Diretora",
  "email": "maria@email.com",
  "password": "123456"
}

###
# @name authenticate
POST {{baseUrl}}/sessions
Content-Type: application/json

{
  "email": "maria@email.com",
  "password": "123456"
}

###
# @name create_problem
POST {{baseUrl}}/problems
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "title": "Ar-condicionado da Sala 01 com defeito",
  "description": "O ar-condicionado da sala 01 não está ligando.",
  "location_id": "location-test",
  "category_id": "category-test"
}

###
# @name fetch_problems
GET {{baseUrl}}/problems?page=1
Content-Type: application/json
Authorization: Bearer {{authToken}}