services:
  postgres:
    container_name: ifal-arapiraca-pg
    image: postgres:16-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: ifal-arapiraca
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
